[package]
name = "rust24k"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
walkdir = "2.3"
kamadak-exif = "0.5.5"
chrono = "0.4"
indicatif = "0.17"

[profile.release]
lto = true
codegen-units = 1
opt-level = 3
